# Generated by Django 2.2.1 on 2019-05-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190507_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseQuantity', models.IntegerField()),
                ('purchaseDescription', models.TextField(null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(editable=False)),
                ('lastModifiedDate', models.DateTimeField(null=True)),
                ('itemId', models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_item', to='core.Item')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
